//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class Recipe01 : Neo.ApplicationFramework.Tools.Recipe.Recipe, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_01;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_02;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_03;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_04;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_05;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_06;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_07;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_08;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_09;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_10;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_11;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_12;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_13;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_14;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_15;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_16;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_17;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_18;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_19;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewID_20;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_01;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_02;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_03;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_04;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_05;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_06;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_07;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_08;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_09;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_10;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_11;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_12;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_13;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_14;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_15;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_16;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_17;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_18;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_19;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosX_20;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosY_01;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosY_02;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosY_03;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosY_04;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosY_05;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosY_06;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosY_07;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosY_08;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosY_09;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosY_10;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosY_11;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeItem52;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeItem53;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeItem54;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeItem55;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeItem56;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeItem57;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeItem58;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeItem59;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeItem60;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_01;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_02;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_03;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_04;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_05;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_06;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_07;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_08;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_09;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_10;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_11;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_12;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_13;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_14;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_15;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_16;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_17;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_18;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_19;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_ScrewPosZ_20;
		
		public Recipe01()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_01
		{
			get
			{
				return this.m_ScrewID_01;
			}
			set
			{
				this.m_ScrewID_01 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_02
		{
			get
			{
				return this.m_ScrewID_02;
			}
			set
			{
				this.m_ScrewID_02 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_03
		{
			get
			{
				return this.m_ScrewID_03;
			}
			set
			{
				this.m_ScrewID_03 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_04
		{
			get
			{
				return this.m_ScrewID_04;
			}
			set
			{
				this.m_ScrewID_04 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_05
		{
			get
			{
				return this.m_ScrewID_05;
			}
			set
			{
				this.m_ScrewID_05 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_06
		{
			get
			{
				return this.m_ScrewID_06;
			}
			set
			{
				this.m_ScrewID_06 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_07
		{
			get
			{
				return this.m_ScrewID_07;
			}
			set
			{
				this.m_ScrewID_07 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_08
		{
			get
			{
				return this.m_ScrewID_08;
			}
			set
			{
				this.m_ScrewID_08 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_09
		{
			get
			{
				return this.m_ScrewID_09;
			}
			set
			{
				this.m_ScrewID_09 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_10
		{
			get
			{
				return this.m_ScrewID_10;
			}
			set
			{
				this.m_ScrewID_10 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_11
		{
			get
			{
				return this.m_ScrewID_11;
			}
			set
			{
				this.m_ScrewID_11 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_12
		{
			get
			{
				return this.m_ScrewID_12;
			}
			set
			{
				this.m_ScrewID_12 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_13
		{
			get
			{
				return this.m_ScrewID_13;
			}
			set
			{
				this.m_ScrewID_13 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_14
		{
			get
			{
				return this.m_ScrewID_14;
			}
			set
			{
				this.m_ScrewID_14 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_15
		{
			get
			{
				return this.m_ScrewID_15;
			}
			set
			{
				this.m_ScrewID_15 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_16
		{
			get
			{
				return this.m_ScrewID_16;
			}
			set
			{
				this.m_ScrewID_16 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_17
		{
			get
			{
				return this.m_ScrewID_17;
			}
			set
			{
				this.m_ScrewID_17 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_18
		{
			get
			{
				return this.m_ScrewID_18;
			}
			set
			{
				this.m_ScrewID_18 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_19
		{
			get
			{
				return this.m_ScrewID_19;
			}
			set
			{
				this.m_ScrewID_19 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewID_20
		{
			get
			{
				return this.m_ScrewID_20;
			}
			set
			{
				this.m_ScrewID_20 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_01
		{
			get
			{
				return this.m_ScrewPosX_01;
			}
			set
			{
				this.m_ScrewPosX_01 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_02
		{
			get
			{
				return this.m_ScrewPosX_02;
			}
			set
			{
				this.m_ScrewPosX_02 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_03
		{
			get
			{
				return this.m_ScrewPosX_03;
			}
			set
			{
				this.m_ScrewPosX_03 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_04
		{
			get
			{
				return this.m_ScrewPosX_04;
			}
			set
			{
				this.m_ScrewPosX_04 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_05
		{
			get
			{
				return this.m_ScrewPosX_05;
			}
			set
			{
				this.m_ScrewPosX_05 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_06
		{
			get
			{
				return this.m_ScrewPosX_06;
			}
			set
			{
				this.m_ScrewPosX_06 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_07
		{
			get
			{
				return this.m_ScrewPosX_07;
			}
			set
			{
				this.m_ScrewPosX_07 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_08
		{
			get
			{
				return this.m_ScrewPosX_08;
			}
			set
			{
				this.m_ScrewPosX_08 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_09
		{
			get
			{
				return this.m_ScrewPosX_09;
			}
			set
			{
				this.m_ScrewPosX_09 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_10
		{
			get
			{
				return this.m_ScrewPosX_10;
			}
			set
			{
				this.m_ScrewPosX_10 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_11
		{
			get
			{
				return this.m_ScrewPosX_11;
			}
			set
			{
				this.m_ScrewPosX_11 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_12
		{
			get
			{
				return this.m_ScrewPosX_12;
			}
			set
			{
				this.m_ScrewPosX_12 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_13
		{
			get
			{
				return this.m_ScrewPosX_13;
			}
			set
			{
				this.m_ScrewPosX_13 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_14
		{
			get
			{
				return this.m_ScrewPosX_14;
			}
			set
			{
				this.m_ScrewPosX_14 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_15
		{
			get
			{
				return this.m_ScrewPosX_15;
			}
			set
			{
				this.m_ScrewPosX_15 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_16
		{
			get
			{
				return this.m_ScrewPosX_16;
			}
			set
			{
				this.m_ScrewPosX_16 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_17
		{
			get
			{
				return this.m_ScrewPosX_17;
			}
			set
			{
				this.m_ScrewPosX_17 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_18
		{
			get
			{
				return this.m_ScrewPosX_18;
			}
			set
			{
				this.m_ScrewPosX_18 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_19
		{
			get
			{
				return this.m_ScrewPosX_19;
			}
			set
			{
				this.m_ScrewPosX_19 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosX_20
		{
			get
			{
				return this.m_ScrewPosX_20;
			}
			set
			{
				this.m_ScrewPosX_20 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosY_01
		{
			get
			{
				return this.m_ScrewPosY_01;
			}
			set
			{
				this.m_ScrewPosY_01 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosY_02
		{
			get
			{
				return this.m_ScrewPosY_02;
			}
			set
			{
				this.m_ScrewPosY_02 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosY_03
		{
			get
			{
				return this.m_ScrewPosY_03;
			}
			set
			{
				this.m_ScrewPosY_03 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosY_04
		{
			get
			{
				return this.m_ScrewPosY_04;
			}
			set
			{
				this.m_ScrewPosY_04 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosY_05
		{
			get
			{
				return this.m_ScrewPosY_05;
			}
			set
			{
				this.m_ScrewPosY_05 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosY_06
		{
			get
			{
				return this.m_ScrewPosY_06;
			}
			set
			{
				this.m_ScrewPosY_06 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosY_07
		{
			get
			{
				return this.m_ScrewPosY_07;
			}
			set
			{
				this.m_ScrewPosY_07 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosY_08
		{
			get
			{
				return this.m_ScrewPosY_08;
			}
			set
			{
				this.m_ScrewPosY_08 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosY_09
		{
			get
			{
				return this.m_ScrewPosY_09;
			}
			set
			{
				this.m_ScrewPosY_09 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosY_10
		{
			get
			{
				return this.m_ScrewPosY_10;
			}
			set
			{
				this.m_ScrewPosY_10 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosY_11
		{
			get
			{
				return this.m_ScrewPosY_11;
			}
			set
			{
				this.m_ScrewPosY_11 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeItem52
		{
			get
			{
				return this.m_RecipeItem52;
			}
			set
			{
				this.m_RecipeItem52 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeItem53
		{
			get
			{
				return this.m_RecipeItem53;
			}
			set
			{
				this.m_RecipeItem53 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeItem54
		{
			get
			{
				return this.m_RecipeItem54;
			}
			set
			{
				this.m_RecipeItem54 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeItem55
		{
			get
			{
				return this.m_RecipeItem55;
			}
			set
			{
				this.m_RecipeItem55 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeItem56
		{
			get
			{
				return this.m_RecipeItem56;
			}
			set
			{
				this.m_RecipeItem56 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeItem57
		{
			get
			{
				return this.m_RecipeItem57;
			}
			set
			{
				this.m_RecipeItem57 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeItem58
		{
			get
			{
				return this.m_RecipeItem58;
			}
			set
			{
				this.m_RecipeItem58 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeItem59
		{
			get
			{
				return this.m_RecipeItem59;
			}
			set
			{
				this.m_RecipeItem59 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeItem60
		{
			get
			{
				return this.m_RecipeItem60;
			}
			set
			{
				this.m_RecipeItem60 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_01
		{
			get
			{
				return this.m_ScrewPosZ_01;
			}
			set
			{
				this.m_ScrewPosZ_01 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_02
		{
			get
			{
				return this.m_ScrewPosZ_02;
			}
			set
			{
				this.m_ScrewPosZ_02 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_03
		{
			get
			{
				return this.m_ScrewPosZ_03;
			}
			set
			{
				this.m_ScrewPosZ_03 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_04
		{
			get
			{
				return this.m_ScrewPosZ_04;
			}
			set
			{
				this.m_ScrewPosZ_04 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_05
		{
			get
			{
				return this.m_ScrewPosZ_05;
			}
			set
			{
				this.m_ScrewPosZ_05 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_06
		{
			get
			{
				return this.m_ScrewPosZ_06;
			}
			set
			{
				this.m_ScrewPosZ_06 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_07
		{
			get
			{
				return this.m_ScrewPosZ_07;
			}
			set
			{
				this.m_ScrewPosZ_07 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_08
		{
			get
			{
				return this.m_ScrewPosZ_08;
			}
			set
			{
				this.m_ScrewPosZ_08 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_09
		{
			get
			{
				return this.m_ScrewPosZ_09;
			}
			set
			{
				this.m_ScrewPosZ_09 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_10
		{
			get
			{
				return this.m_ScrewPosZ_10;
			}
			set
			{
				this.m_ScrewPosZ_10 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_11
		{
			get
			{
				return this.m_ScrewPosZ_11;
			}
			set
			{
				this.m_ScrewPosZ_11 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_12
		{
			get
			{
				return this.m_ScrewPosZ_12;
			}
			set
			{
				this.m_ScrewPosZ_12 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_13
		{
			get
			{
				return this.m_ScrewPosZ_13;
			}
			set
			{
				this.m_ScrewPosZ_13 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_14
		{
			get
			{
				return this.m_ScrewPosZ_14;
			}
			set
			{
				this.m_ScrewPosZ_14 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_15
		{
			get
			{
				return this.m_ScrewPosZ_15;
			}
			set
			{
				this.m_ScrewPosZ_15 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_16
		{
			get
			{
				return this.m_ScrewPosZ_16;
			}
			set
			{
				this.m_ScrewPosZ_16 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_17
		{
			get
			{
				return this.m_ScrewPosZ_17;
			}
			set
			{
				this.m_ScrewPosZ_17 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_18
		{
			get
			{
				return this.m_ScrewPosZ_18;
			}
			set
			{
				this.m_ScrewPosZ_18 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_19
		{
			get
			{
				return this.m_ScrewPosZ_19;
			}
			set
			{
				this.m_ScrewPosZ_19 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem ScrewPosZ_20
		{
			get
			{
				return this.m_ScrewPosZ_20;
			}
			set
			{
				this.m_ScrewPosZ_20 = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
			this.ScrewID_01 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_02 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_03 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_04 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_05 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_06 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_07 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_08 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_09 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_10 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_11 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_12 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_13 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_14 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_15 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_16 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_17 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_18 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_19 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewID_20 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_01 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_02 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_03 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_04 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_05 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_06 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_07 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_08 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_09 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_10 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_11 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_12 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_13 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_14 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_15 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_16 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_17 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_18 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_19 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosX_20 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosY_01 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosY_02 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosY_03 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosY_04 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosY_05 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosY_06 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosY_07 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosY_08 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosY_09 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosY_10 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosY_11 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeItem52 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeItem53 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeItem54 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeItem55 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeItem56 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeItem57 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeItem58 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeItem59 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeItem60 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_01 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_02 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_03 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_04 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_05 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_06 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_07 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_08 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_09 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_10 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_11 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_12 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_13 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_14 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_15 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_16 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_17 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_18 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_19 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.ScrewPosZ_20 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.DataVersion = ((long)(75));
			this.FieldNames.Add("Model#ABCDEFGH01");
			this.FieldNames.Add("Model#ABCDEFGH02");
			this.FieldNames.Add("Model#ABCDEFGH04");
			this.FieldNames.Add("Model#ABCDEFGH05");
			this.FieldNames.Add("Model#ABCDEFGH06");
			this.FieldNames.Add("Model#ABCDEFGH07");
			this.FieldNames.Add("Model#ABCDEFGH08");
			this.FieldNames.Add("Model#ABCDEFGH09");
			this.FieldNames.Add("Model#ABCDEFGH10");
			this.FieldNames.Add("Model#ABCDEFGH03");
			this.Guid = new System.Guid("7ce5a932-5d66-4173-aa0f-b2b808737c73");
			this.ScrewID_01.ColumnName = "ScrewID_01";
			this.ScrewID_01.DataConnection = "Tags.ScrewID_01";
			this.ScrewID_01.Name = "ScrewID_01";
			this.ScrewID_01.VisualSortOrder = 1;
			this.ScrewID_02.ColumnName = "ScrewID_02";
			this.ScrewID_02.DataConnection = "Tags.ScrewID_02";
			this.ScrewID_02.Name = "ScrewID_02";
			this.ScrewID_02.VisualSortOrder = 2;
			this.ScrewID_03.ColumnName = "ScrewID_03";
			this.ScrewID_03.DataConnection = "Tags.ScrewID_03";
			this.ScrewID_03.Name = "ScrewID_03";
			this.ScrewID_03.VisualSortOrder = 3;
			this.ScrewID_04.ColumnName = "ScrewID_04";
			this.ScrewID_04.DataConnection = "Tags.ScrewID_04";
			this.ScrewID_04.Name = "ScrewID_04";
			this.ScrewID_04.VisualSortOrder = 4;
			this.ScrewID_05.ColumnName = "ScrewID_05";
			this.ScrewID_05.DataConnection = "Tags.ScrewID_05";
			this.ScrewID_05.Name = "ScrewID_05";
			this.ScrewID_05.VisualSortOrder = 5;
			this.ScrewID_06.ColumnName = "ScrewID_06";
			this.ScrewID_06.DataConnection = "Tags.ScrewID_06";
			this.ScrewID_06.Name = "ScrewID_06";
			this.ScrewID_06.VisualSortOrder = 6;
			this.ScrewID_07.ColumnName = "ScrewID_07";
			this.ScrewID_07.DataConnection = "Tags.ScrewID_07";
			this.ScrewID_07.Name = "ScrewID_07";
			this.ScrewID_07.VisualSortOrder = 7;
			this.ScrewID_08.ColumnName = "ScrewID_08";
			this.ScrewID_08.DataConnection = "Tags.ScrewID_08";
			this.ScrewID_08.Name = "ScrewID_08";
			this.ScrewID_08.VisualSortOrder = 8;
			this.ScrewID_09.ColumnName = "ScrewID_09";
			this.ScrewID_09.DataConnection = "Tags.ScrewID_09";
			this.ScrewID_09.Name = "ScrewID_09";
			this.ScrewID_09.VisualSortOrder = 9;
			this.ScrewID_10.ColumnName = "ScrewID_10";
			this.ScrewID_10.DataConnection = "Tags.ScrewID_10";
			this.ScrewID_10.Name = "ScrewID_10";
			this.ScrewID_10.VisualSortOrder = 10;
			this.ScrewID_11.ColumnName = "ScrewID_11";
			this.ScrewID_11.DataConnection = "Tags.ScrewID_11";
			this.ScrewID_11.Name = "ScrewID_11";
			this.ScrewID_11.VisualSortOrder = 11;
			this.ScrewID_12.ColumnName = "ScrewID_12";
			this.ScrewID_12.DataConnection = "Tags.ScrewID_12";
			this.ScrewID_12.Name = "ScrewID_12";
			this.ScrewID_12.VisualSortOrder = 12;
			this.ScrewID_13.ColumnName = "ScrewID_13";
			this.ScrewID_13.DataConnection = "Tags.ScrewID_13";
			this.ScrewID_13.Name = "ScrewID_13";
			this.ScrewID_13.VisualSortOrder = 13;
			this.ScrewID_14.ColumnName = "ScrewID_14";
			this.ScrewID_14.DataConnection = "Tags.ScrewID_14";
			this.ScrewID_14.Name = "ScrewID_14";
			this.ScrewID_14.VisualSortOrder = 14;
			this.ScrewID_15.ColumnName = "ScrewID_15";
			this.ScrewID_15.DataConnection = "Tags.ScrewID_15";
			this.ScrewID_15.Name = "ScrewID_15";
			this.ScrewID_15.VisualSortOrder = 15;
			this.ScrewID_16.ColumnName = "ScrewID_16";
			this.ScrewID_16.DataConnection = "Tags.ScrewID_16";
			this.ScrewID_16.Name = "ScrewID_16";
			this.ScrewID_16.VisualSortOrder = 16;
			this.ScrewID_17.ColumnName = "ScrewID_17";
			this.ScrewID_17.DataConnection = "Tags.ScrewID_17";
			this.ScrewID_17.Name = "ScrewID_17";
			this.ScrewID_17.VisualSortOrder = 17;
			this.ScrewID_18.ColumnName = "ScrewID_18";
			this.ScrewID_18.DataConnection = "Tags.ScrewID_18";
			this.ScrewID_18.Name = "ScrewID_18";
			this.ScrewID_18.VisualSortOrder = 18;
			this.ScrewID_19.ColumnName = "ScrewID_19";
			this.ScrewID_19.DataConnection = "Tags.ScrewID_19";
			this.ScrewID_19.Name = "ScrewID_19";
			this.ScrewID_19.VisualSortOrder = 19;
			this.ScrewID_20.ColumnName = "ScrewID_20";
			this.ScrewID_20.DataConnection = "Tags.ScrewID_20";
			this.ScrewID_20.Name = "ScrewID_20";
			this.ScrewID_20.VisualSortOrder = 20;
			this.ScrewPosX_01.ColumnName = "ScrewPosX_01";
			this.ScrewPosX_01.DataConnection = "Tags.ScrewPosX_01";
			this.ScrewPosX_01.Name = "ScrewPosX_01";
			this.ScrewPosX_01.VisualSortOrder = 21;
			this.ScrewPosX_02.ColumnName = "ScrewPosX_02";
			this.ScrewPosX_02.DataConnection = "Tags.ScrewPosX_02";
			this.ScrewPosX_02.Name = "ScrewPosX_02";
			this.ScrewPosX_02.VisualSortOrder = 22;
			this.ScrewPosX_03.ColumnName = "ScrewPosX_03";
			this.ScrewPosX_03.DataConnection = "Tags.ScrewPosX_03";
			this.ScrewPosX_03.Name = "ScrewPosX_03";
			this.ScrewPosX_03.VisualSortOrder = 23;
			this.ScrewPosX_04.ColumnName = "ScrewPosX_04";
			this.ScrewPosX_04.DataConnection = "Tags.ScrewPosX_04";
			this.ScrewPosX_04.Name = "ScrewPosX_04";
			this.ScrewPosX_04.VisualSortOrder = 24;
			this.ScrewPosX_05.ColumnName = "ScrewPosX_05";
			this.ScrewPosX_05.DataConnection = "Tags.ScrewPosX_05";
			this.ScrewPosX_05.Name = "ScrewPosX_05";
			this.ScrewPosX_05.VisualSortOrder = 25;
			this.ScrewPosX_06.ColumnName = "ScrewPosX_06";
			this.ScrewPosX_06.DataConnection = "Tags.ScrewPosX_06";
			this.ScrewPosX_06.Name = "ScrewPosX_06";
			this.ScrewPosX_06.VisualSortOrder = 26;
			this.ScrewPosX_07.ColumnName = "ScrewPosX_07";
			this.ScrewPosX_07.DataConnection = "Tags.ScrewPosX_07";
			this.ScrewPosX_07.Name = "ScrewPosX_07";
			this.ScrewPosX_07.VisualSortOrder = 27;
			this.ScrewPosX_08.ColumnName = "ScrewPosX_08";
			this.ScrewPosX_08.DataConnection = "Tags.ScrewPosX_08";
			this.ScrewPosX_08.Name = "ScrewPosX_08";
			this.ScrewPosX_08.VisualSortOrder = 28;
			this.ScrewPosX_09.ColumnName = "ScrewPosX_09";
			this.ScrewPosX_09.DataConnection = "Tags.ScrewPosX_09";
			this.ScrewPosX_09.Name = "ScrewPosX_09";
			this.ScrewPosX_09.VisualSortOrder = 29;
			this.ScrewPosX_10.ColumnName = "ScrewPosX_10";
			this.ScrewPosX_10.DataConnection = "Tags.ScrewPosX_10";
			this.ScrewPosX_10.Name = "ScrewPosX_10";
			this.ScrewPosX_10.VisualSortOrder = 30;
			this.ScrewPosX_11.ColumnName = "ScrewPosX_11";
			this.ScrewPosX_11.DataConnection = "Tags.ScrewPosX_11";
			this.ScrewPosX_11.Name = "ScrewPosX_11";
			this.ScrewPosX_11.VisualSortOrder = 31;
			this.ScrewPosX_12.ColumnName = "ScrewPosX_12";
			this.ScrewPosX_12.DataConnection = "Tags.ScrewPosX_12";
			this.ScrewPosX_12.Name = "ScrewPosX_12";
			this.ScrewPosX_12.VisualSortOrder = 32;
			this.ScrewPosX_13.ColumnName = "ScrewPosX_13";
			this.ScrewPosX_13.DataConnection = "Tags.ScrewPosX_13";
			this.ScrewPosX_13.Name = "ScrewPosX_13";
			this.ScrewPosX_13.VisualSortOrder = 33;
			this.ScrewPosX_14.ColumnName = "ScrewPosX_14";
			this.ScrewPosX_14.DataConnection = "Tags.ScrewPosX_14";
			this.ScrewPosX_14.Name = "ScrewPosX_14";
			this.ScrewPosX_14.VisualSortOrder = 34;
			this.ScrewPosX_15.ColumnName = "ScrewPosX_15";
			this.ScrewPosX_15.DataConnection = "Tags.ScrewPosX_15";
			this.ScrewPosX_15.Name = "ScrewPosX_15";
			this.ScrewPosX_15.VisualSortOrder = 35;
			this.ScrewPosX_16.ColumnName = "ScrewPosX_16";
			this.ScrewPosX_16.DataConnection = "Tags.ScrewPosX_16";
			this.ScrewPosX_16.Name = "ScrewPosX_16";
			this.ScrewPosX_16.VisualSortOrder = 36;
			this.ScrewPosX_17.ColumnName = "ScrewPosX_17";
			this.ScrewPosX_17.DataConnection = "Tags.ScrewPosX_17";
			this.ScrewPosX_17.Name = "ScrewPosX_17";
			this.ScrewPosX_17.VisualSortOrder = 37;
			this.ScrewPosX_18.ColumnName = "ScrewPosX_18";
			this.ScrewPosX_18.DataConnection = "Tags.ScrewPosX_18";
			this.ScrewPosX_18.Name = "ScrewPosX_18";
			this.ScrewPosX_18.VisualSortOrder = 38;
			this.ScrewPosX_19.ColumnName = "ScrewPosX_19";
			this.ScrewPosX_19.DataConnection = "Tags.ScrewPosX_19";
			this.ScrewPosX_19.Name = "ScrewPosX_19";
			this.ScrewPosX_19.VisualSortOrder = 39;
			this.ScrewPosX_20.ColumnName = "ScrewPosX_20";
			this.ScrewPosX_20.DataConnection = "Tags.ScrewPosX_20";
			this.ScrewPosX_20.Name = "ScrewPosX_20";
			this.ScrewPosX_20.VisualSortOrder = 40;
			this.ScrewPosY_01.ColumnName = "ScrewPosY_01";
			this.ScrewPosY_01.DataConnection = "Tags.ScrewPosY_01";
			this.ScrewPosY_01.Name = "ScrewPosY_01";
			this.ScrewPosY_01.VisualSortOrder = 41;
			this.ScrewPosY_02.ColumnName = "ScrewPosY_02";
			this.ScrewPosY_02.DataConnection = "Tags.ScrewPosY_02";
			this.ScrewPosY_02.Name = "ScrewPosY_02";
			this.ScrewPosY_02.VisualSortOrder = 42;
			this.ScrewPosY_03.ColumnName = "ScrewPosY_03";
			this.ScrewPosY_03.DataConnection = "Tags.ScrewPosY_03";
			this.ScrewPosY_03.Name = "ScrewPosY_03";
			this.ScrewPosY_03.VisualSortOrder = 43;
			this.ScrewPosY_04.ColumnName = "ScrewPosY_04";
			this.ScrewPosY_04.DataConnection = "Tags.ScrewPosY_04";
			this.ScrewPosY_04.Name = "ScrewPosY_04";
			this.ScrewPosY_04.VisualSortOrder = 44;
			this.ScrewPosY_05.ColumnName = "ScrewPosY_05";
			this.ScrewPosY_05.DataConnection = "Tags.ScrewPosY_05";
			this.ScrewPosY_05.Name = "ScrewPosY_05";
			this.ScrewPosY_05.VisualSortOrder = 45;
			this.ScrewPosY_06.ColumnName = "ScrewPosY_06";
			this.ScrewPosY_06.DataConnection = "Tags.ScrewPosY_06";
			this.ScrewPosY_06.Name = "ScrewPosY_06";
			this.ScrewPosY_06.VisualSortOrder = 46;
			this.ScrewPosY_07.ColumnName = "ScrewPosY_07";
			this.ScrewPosY_07.DataConnection = "Tags.ScrewPosY_07";
			this.ScrewPosY_07.Name = "ScrewPosY_07";
			this.ScrewPosY_07.VisualSortOrder = 47;
			this.ScrewPosY_08.ColumnName = "ScrewPosY_08";
			this.ScrewPosY_08.DataConnection = "Tags.ScrewPosY_08";
			this.ScrewPosY_08.Name = "ScrewPosY_08";
			this.ScrewPosY_08.VisualSortOrder = 48;
			this.ScrewPosY_09.ColumnName = "ScrewPosY_09";
			this.ScrewPosY_09.DataConnection = "Tags.ScrewPosY_09";
			this.ScrewPosY_09.Name = "ScrewPosY_09";
			this.ScrewPosY_09.VisualSortOrder = 49;
			this.ScrewPosY_10.ColumnName = "ScrewPosY_10";
			this.ScrewPosY_10.DataConnection = "Tags.ScrewPosY_10";
			this.ScrewPosY_10.Name = "ScrewPosY_10";
			this.ScrewPosY_10.VisualSortOrder = 50;
			this.ScrewPosY_11.ColumnName = "ScrewPosY_11";
			this.ScrewPosY_11.DataConnection = "Tags.ScrewPosY_11";
			this.ScrewPosY_11.Name = "ScrewPosY_11";
			this.ScrewPosY_11.VisualSortOrder = 51;
			this.RecipeItem52.ColumnName = "RecipeItem52";
			this.RecipeItem52.DataConnection = "Tags.ScrewPosY_12";
			this.RecipeItem52.Name = "RecipeItem52";
			this.RecipeItem52.VisualSortOrder = 52;
			this.RecipeItem53.ColumnName = "RecipeItem53";
			this.RecipeItem53.DataConnection = "Tags.ScrewPosY_13";
			this.RecipeItem53.Name = "RecipeItem53";
			this.RecipeItem53.VisualSortOrder = 53;
			this.RecipeItem54.ColumnName = "RecipeItem54";
			this.RecipeItem54.DataConnection = "Tags.ScrewPosY_14";
			this.RecipeItem54.Name = "RecipeItem54";
			this.RecipeItem54.VisualSortOrder = 54;
			this.RecipeItem55.ColumnName = "RecipeItem55";
			this.RecipeItem55.DataConnection = "Tags.ScrewPosY_15";
			this.RecipeItem55.Name = "RecipeItem55";
			this.RecipeItem55.VisualSortOrder = 55;
			this.RecipeItem56.ColumnName = "RecipeItem56";
			this.RecipeItem56.DataConnection = "Tags.ScrewPosY_16";
			this.RecipeItem56.Name = "RecipeItem56";
			this.RecipeItem56.VisualSortOrder = 56;
			this.RecipeItem57.ColumnName = "RecipeItem57";
			this.RecipeItem57.DataConnection = "Tags.ScrewPosY_17";
			this.RecipeItem57.Name = "RecipeItem57";
			this.RecipeItem57.VisualSortOrder = 57;
			this.RecipeItem58.ColumnName = "RecipeItem58";
			this.RecipeItem58.DataConnection = "Tags.ScrewPosY_18";
			this.RecipeItem58.Name = "RecipeItem58";
			this.RecipeItem58.VisualSortOrder = 58;
			this.RecipeItem59.ColumnName = "RecipeItem59";
			this.RecipeItem59.DataConnection = "Tags.ScrewPosY_19";
			this.RecipeItem59.Name = "RecipeItem59";
			this.RecipeItem59.VisualSortOrder = 59;
			this.RecipeItem60.ColumnName = "RecipeItem60";
			this.RecipeItem60.DataConnection = "Tags.ScrewPosY_20";
			this.RecipeItem60.Name = "RecipeItem60";
			this.RecipeItem60.VisualSortOrder = 60;
			this.ScrewPosZ_01.ColumnName = "ScrewPosZ_01";
			this.ScrewPosZ_01.DataConnection = "Tags.ScrewPosZ_01";
			this.ScrewPosZ_01.Name = "ScrewPosZ_01";
			this.ScrewPosZ_01.VisualSortOrder = 61;
			this.ScrewPosZ_02.ColumnName = "ScrewPosZ_02";
			this.ScrewPosZ_02.DataConnection = "Tags.ScrewPosZ_02";
			this.ScrewPosZ_02.Name = "ScrewPosZ_02";
			this.ScrewPosZ_02.VisualSortOrder = 62;
			this.ScrewPosZ_03.ColumnName = "ScrewPosZ_03";
			this.ScrewPosZ_03.DataConnection = "Tags.ScrewPosZ_03";
			this.ScrewPosZ_03.Name = "ScrewPosZ_03";
			this.ScrewPosZ_03.VisualSortOrder = 63;
			this.ScrewPosZ_04.ColumnName = "ScrewPosZ_04";
			this.ScrewPosZ_04.DataConnection = "Tags.ScrewPosZ_04";
			this.ScrewPosZ_04.Name = "ScrewPosZ_04";
			this.ScrewPosZ_04.VisualSortOrder = 64;
			this.ScrewPosZ_05.ColumnName = "ScrewPosZ_05";
			this.ScrewPosZ_05.DataConnection = "Tags.ScrewPosZ_05";
			this.ScrewPosZ_05.Name = "ScrewPosZ_05";
			this.ScrewPosZ_05.VisualSortOrder = 65;
			this.ScrewPosZ_06.ColumnName = "ScrewPosZ_06";
			this.ScrewPosZ_06.DataConnection = "Tags.ScrewPosZ_06";
			this.ScrewPosZ_06.Name = "ScrewPosZ_06";
			this.ScrewPosZ_06.VisualSortOrder = 66;
			this.ScrewPosZ_07.ColumnName = "ScrewPosZ_07";
			this.ScrewPosZ_07.DataConnection = "Tags.ScrewPosZ_07";
			this.ScrewPosZ_07.Name = "ScrewPosZ_07";
			this.ScrewPosZ_07.VisualSortOrder = 67;
			this.ScrewPosZ_08.ColumnName = "ScrewPosZ_08";
			this.ScrewPosZ_08.DataConnection = "Tags.ScrewPosZ_08";
			this.ScrewPosZ_08.Name = "ScrewPosZ_08";
			this.ScrewPosZ_08.VisualSortOrder = 68;
			this.ScrewPosZ_09.ColumnName = "ScrewPosZ_09";
			this.ScrewPosZ_09.DataConnection = "Tags.ScrewPosZ_09";
			this.ScrewPosZ_09.Name = "ScrewPosZ_09";
			this.ScrewPosZ_09.VisualSortOrder = 69;
			this.ScrewPosZ_10.ColumnName = "ScrewPosZ_10";
			this.ScrewPosZ_10.DataConnection = "Tags.ScrewPosZ_10";
			this.ScrewPosZ_10.Name = "ScrewPosZ_10";
			this.ScrewPosZ_10.VisualSortOrder = 70;
			this.ScrewPosZ_11.ColumnName = "ScrewPosZ_11";
			this.ScrewPosZ_11.DataConnection = "Tags.ScrewPosZ_11";
			this.ScrewPosZ_11.Name = "ScrewPosZ_11";
			this.ScrewPosZ_11.VisualSortOrder = 71;
			this.ScrewPosZ_12.ColumnName = "ScrewPosZ_12";
			this.ScrewPosZ_12.DataConnection = "Tags.ScrewPosZ_12";
			this.ScrewPosZ_12.Name = "ScrewPosZ_12";
			this.ScrewPosZ_12.VisualSortOrder = 72;
			this.ScrewPosZ_13.ColumnName = "ScrewPosZ_13";
			this.ScrewPosZ_13.DataConnection = "Tags.ScrewPosZ_13";
			this.ScrewPosZ_13.Name = "ScrewPosZ_13";
			this.ScrewPosZ_13.VisualSortOrder = 73;
			this.ScrewPosZ_14.ColumnName = "ScrewPosZ_14";
			this.ScrewPosZ_14.DataConnection = "Tags.ScrewPosZ_14";
			this.ScrewPosZ_14.Name = "ScrewPosZ_14";
			this.ScrewPosZ_14.VisualSortOrder = 74;
			this.ScrewPosZ_15.ColumnName = "ScrewPosZ_15";
			this.ScrewPosZ_15.DataConnection = "Tags.ScrewPosZ_15";
			this.ScrewPosZ_15.Name = "ScrewPosZ_15";
			this.ScrewPosZ_15.VisualSortOrder = 75;
			this.ScrewPosZ_16.ColumnName = "ScrewPosZ_16";
			this.ScrewPosZ_16.DataConnection = "Tags.ScrewPosZ_16";
			this.ScrewPosZ_16.Name = "ScrewPosZ_16";
			this.ScrewPosZ_16.VisualSortOrder = 76;
			this.ScrewPosZ_17.ColumnName = "ScrewPosZ_17";
			this.ScrewPosZ_17.DataConnection = "Tags.ScrewPosZ_17";
			this.ScrewPosZ_17.Name = "ScrewPosZ_17";
			this.ScrewPosZ_17.VisualSortOrder = 77;
			this.ScrewPosZ_18.ColumnName = "ScrewPosZ_18";
			this.ScrewPosZ_18.DataConnection = "Tags.ScrewPosZ_18";
			this.ScrewPosZ_18.Name = "ScrewPosZ_18";
			this.ScrewPosZ_18.VisualSortOrder = 78;
			this.ScrewPosZ_19.ColumnName = "ScrewPosZ_19";
			this.ScrewPosZ_19.DataConnection = "Tags.ScrewPosZ_19";
			this.ScrewPosZ_19.Name = "ScrewPosZ_19";
			this.ScrewPosZ_19.VisualSortOrder = 79;
			this.ScrewPosZ_20.ColumnName = "ScrewPosZ_20";
			this.ScrewPosZ_20.DataConnection = "Tags.ScrewPosZ_20";
			this.ScrewPosZ_20.Name = "ScrewPosZ_20";
			this.ScrewPosZ_20.VisualSortOrder = 80;
			this.RecipeItems.Add(this.ScrewID_01);
			this.RecipeItems.Add(this.ScrewID_02);
			this.RecipeItems.Add(this.ScrewID_03);
			this.RecipeItems.Add(this.ScrewID_04);
			this.RecipeItems.Add(this.ScrewID_05);
			this.RecipeItems.Add(this.ScrewID_06);
			this.RecipeItems.Add(this.ScrewID_07);
			this.RecipeItems.Add(this.ScrewID_08);
			this.RecipeItems.Add(this.ScrewID_09);
			this.RecipeItems.Add(this.ScrewID_10);
			this.RecipeItems.Add(this.ScrewID_11);
			this.RecipeItems.Add(this.ScrewID_12);
			this.RecipeItems.Add(this.ScrewID_13);
			this.RecipeItems.Add(this.ScrewID_14);
			this.RecipeItems.Add(this.ScrewID_15);
			this.RecipeItems.Add(this.ScrewID_16);
			this.RecipeItems.Add(this.ScrewID_17);
			this.RecipeItems.Add(this.ScrewID_18);
			this.RecipeItems.Add(this.ScrewID_19);
			this.RecipeItems.Add(this.ScrewID_20);
			this.RecipeItems.Add(this.ScrewPosX_01);
			this.RecipeItems.Add(this.ScrewPosX_02);
			this.RecipeItems.Add(this.ScrewPosX_03);
			this.RecipeItems.Add(this.ScrewPosX_04);
			this.RecipeItems.Add(this.ScrewPosX_05);
			this.RecipeItems.Add(this.ScrewPosX_06);
			this.RecipeItems.Add(this.ScrewPosX_07);
			this.RecipeItems.Add(this.ScrewPosX_08);
			this.RecipeItems.Add(this.ScrewPosX_09);
			this.RecipeItems.Add(this.ScrewPosX_10);
			this.RecipeItems.Add(this.ScrewPosX_11);
			this.RecipeItems.Add(this.ScrewPosX_12);
			this.RecipeItems.Add(this.ScrewPosX_13);
			this.RecipeItems.Add(this.ScrewPosX_14);
			this.RecipeItems.Add(this.ScrewPosX_15);
			this.RecipeItems.Add(this.ScrewPosX_16);
			this.RecipeItems.Add(this.ScrewPosX_17);
			this.RecipeItems.Add(this.ScrewPosX_18);
			this.RecipeItems.Add(this.ScrewPosX_19);
			this.RecipeItems.Add(this.ScrewPosX_20);
			this.RecipeItems.Add(this.ScrewPosY_01);
			this.RecipeItems.Add(this.ScrewPosY_02);
			this.RecipeItems.Add(this.ScrewPosY_03);
			this.RecipeItems.Add(this.ScrewPosY_04);
			this.RecipeItems.Add(this.ScrewPosY_05);
			this.RecipeItems.Add(this.ScrewPosY_06);
			this.RecipeItems.Add(this.ScrewPosY_07);
			this.RecipeItems.Add(this.ScrewPosY_08);
			this.RecipeItems.Add(this.ScrewPosY_09);
			this.RecipeItems.Add(this.ScrewPosY_10);
			this.RecipeItems.Add(this.ScrewPosY_11);
			this.RecipeItems.Add(this.RecipeItem52);
			this.RecipeItems.Add(this.RecipeItem53);
			this.RecipeItems.Add(this.RecipeItem54);
			this.RecipeItems.Add(this.RecipeItem55);
			this.RecipeItems.Add(this.RecipeItem56);
			this.RecipeItems.Add(this.RecipeItem57);
			this.RecipeItems.Add(this.RecipeItem58);
			this.RecipeItems.Add(this.RecipeItem59);
			this.RecipeItems.Add(this.RecipeItem60);
			this.RecipeItems.Add(this.ScrewPosZ_01);
			this.RecipeItems.Add(this.ScrewPosZ_02);
			this.RecipeItems.Add(this.ScrewPosZ_03);
			this.RecipeItems.Add(this.ScrewPosZ_04);
			this.RecipeItems.Add(this.ScrewPosZ_05);
			this.RecipeItems.Add(this.ScrewPosZ_06);
			this.RecipeItems.Add(this.ScrewPosZ_07);
			this.RecipeItems.Add(this.ScrewPosZ_08);
			this.RecipeItems.Add(this.ScrewPosZ_09);
			this.RecipeItems.Add(this.ScrewPosZ_10);
			this.RecipeItems.Add(this.ScrewPosZ_11);
			this.RecipeItems.Add(this.ScrewPosZ_12);
			this.RecipeItems.Add(this.ScrewPosZ_13);
			this.RecipeItems.Add(this.ScrewPosZ_14);
			this.RecipeItems.Add(this.ScrewPosZ_15);
			this.RecipeItems.Add(this.ScrewPosZ_16);
			this.RecipeItems.Add(this.ScrewPosZ_17);
			this.RecipeItems.Add(this.ScrewPosZ_18);
			this.RecipeItems.Add(this.ScrewPosZ_19);
			this.RecipeItems.Add(this.ScrewPosZ_20);
			this.SchemaVersion = ((long)(343));
			this.TableName = "Recipe01";
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Recipe01));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
