//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class Tags : Neo.ApplicationFramework.Tools.OpcClient.GlobalController, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagLatestLoadedRecipeName;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Tag01;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag StartTime1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag StartTime2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag StartTime3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag StartTime4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag StartTime5;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag StartTime6;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag StartTime7;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag StartTime8;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosX_01;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosX_02;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosX_03;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosX_04;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosX_05;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosX_06;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosX_07;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosX_08;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosX_09;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosX_10;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosX_11;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosX_12;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosX_13;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosX_14;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosX_15;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosX_16;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosX_17;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosX_18;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosX_19;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosX_20;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosY_01;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosY_02;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_03;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosY_04;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosY_05;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_06;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_07;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_08;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_09;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_10;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_11;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_12;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_13;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_14;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_15;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_16;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_17;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_18;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_19;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosY_20;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosZ_01;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosZ_02;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_03;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosZ_04;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewPosZ_05;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_06;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_07;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_08;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_09;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_10;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_11;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_12;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_13;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_14;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_15;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_16;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_17;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_18;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_19;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewPosZ_20;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewID_01;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewID_02;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewID_03;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewID_04;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewID_05;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewID_06;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewID_07;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewID_08;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewID_09;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem ScrewID_10;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewID_11;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewID_12;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewID_13;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewID_14;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewID_15;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewID_16;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewID_17;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewID_18;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewID_19;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag ScrewID_20;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem Tag02;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup5;
		
		public Tags()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
			this.SystemTagLatestLoadedRecipeName = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Latest Loaded Recipe Name", "SystemTagLatestLoadedRecipeName", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), ((short)(100)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Name of the latest loaded recipe", ((short)(1)), "", "");
			this.Tag01 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Tag01", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.StartTime1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("StartTime1", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.StartTime2 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("StartTime2", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.StartTime3 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("StartTime3", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.StartTime4 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("StartTime4", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.StartTime5 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("StartTime5", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.StartTime6 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("StartTime6", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.StartTime7 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("StartTime7", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.StartTime8 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("StartTime8", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.ScrewPosX_01 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosX_01", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosX_02 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosX_02", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosX_03 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosX_03", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosX_04 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosX_04", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosX_05 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosX_05", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosX_06 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosX_06", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosX_07 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosX_07", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosX_08 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosX_08", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosX_09 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosX_09", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosX_10 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosX_10", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosX_11 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosX_11", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosX_12 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosX_12", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosX_13 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosX_13", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosX_14 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosX_14", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosX_15 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosX_15", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosX_16 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosX_16", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosX_17 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosX_17", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosX_18 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosX_18", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosX_19 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosX_19", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosX_20 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosX_20", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_01 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosY_01", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosY_02 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosY_02", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosY_03 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_03", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_04 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosY_04", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosY_05 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosY_05", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosY_06 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_06", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_07 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_07", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_08 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_08", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_09 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_09", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_10 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_10", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_11 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_11", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_12 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_12", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_13 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_13", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_14 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_14", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_15 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_15", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_16 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_16", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_17 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_17", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_18 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_18", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_19 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_19", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosY_20 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosY_20", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_01 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosZ_01", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosZ_02 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosZ_02", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosZ_03 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_03", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_04 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosZ_04", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosZ_05 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewPosZ_05", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewPosZ_06 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_06", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_07 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_07", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_08 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_08", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_09 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_09", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_10 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_10", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_11 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_11", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_12 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_12", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_13 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_13", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_14 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_14", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_15 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_15", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_16 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_16", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_17 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_17", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_18 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_18", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_19 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_19", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewPosZ_20 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewPosZ_20", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewID_01 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewID_01", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewID_02 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewID_02", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewID_03 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewID_03", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewID_04 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewID_04", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewID_05 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewID_05", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewID_06 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewID_06", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewID_07 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewID_07", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewID_08 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewID_08", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewID_09 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewID_09", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewID_10 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("ScrewID_10", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.ScrewID_11 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewID_11", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewID_12 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewID_12", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewID_13 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewID_13", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewID_14 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewID_14", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewID_15 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewID_15", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewID_16 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewID_16", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewID_17 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewID_17", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewID_18 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewID_18", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewID_19 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewID_19", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.ScrewID_20 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("ScrewID_20", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.Tag02 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("Tag02", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.PollGroup1 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup2 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup3 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup4 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup5 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.SystemTagLatestLoadedRecipeName.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Tag01.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosX_01.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosX_02.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosX_03.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosX_04.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosX_05.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosX_06.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosX_07.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosX_08.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosX_09.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosX_10.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosY_01.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosY_02.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosY_04.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosY_05.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosZ_01.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosZ_02.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosZ_04.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewPosZ_05.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewID_01.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewID_02.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewID_03.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewID_04.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewID_05.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewID_06.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewID_07.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewID_08.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewID_09.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.ScrewID_10.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.Tag02.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.GlobalDataItems.Add(this.SystemTagLatestLoadedRecipeName);
			this.GlobalDataItems.Add(this.Tag01);
			this.LightweightTags.Add(this.StartTime1);
			this.LightweightTags.Add(this.StartTime2);
			this.LightweightTags.Add(this.StartTime3);
			this.LightweightTags.Add(this.StartTime4);
			this.LightweightTags.Add(this.StartTime5);
			this.LightweightTags.Add(this.StartTime6);
			this.LightweightTags.Add(this.StartTime7);
			this.LightweightTags.Add(this.StartTime8);
			this.GlobalDataItems.Add(this.ScrewPosX_01);
			this.GlobalDataItems.Add(this.ScrewPosX_02);
			this.GlobalDataItems.Add(this.ScrewPosX_03);
			this.GlobalDataItems.Add(this.ScrewPosX_04);
			this.GlobalDataItems.Add(this.ScrewPosX_05);
			this.GlobalDataItems.Add(this.ScrewPosX_06);
			this.GlobalDataItems.Add(this.ScrewPosX_07);
			this.GlobalDataItems.Add(this.ScrewPosX_08);
			this.GlobalDataItems.Add(this.ScrewPosX_09);
			this.GlobalDataItems.Add(this.ScrewPosX_10);
			this.LightweightTags.Add(this.ScrewPosX_11);
			this.LightweightTags.Add(this.ScrewPosX_12);
			this.LightweightTags.Add(this.ScrewPosX_13);
			this.LightweightTags.Add(this.ScrewPosX_14);
			this.LightweightTags.Add(this.ScrewPosX_15);
			this.LightweightTags.Add(this.ScrewPosX_16);
			this.LightweightTags.Add(this.ScrewPosX_17);
			this.LightweightTags.Add(this.ScrewPosX_18);
			this.LightweightTags.Add(this.ScrewPosX_19);
			this.LightweightTags.Add(this.ScrewPosX_20);
			this.GlobalDataItems.Add(this.ScrewPosY_01);
			this.GlobalDataItems.Add(this.ScrewPosY_02);
			this.LightweightTags.Add(this.ScrewPosY_03);
			this.GlobalDataItems.Add(this.ScrewPosY_04);
			this.GlobalDataItems.Add(this.ScrewPosY_05);
			this.LightweightTags.Add(this.ScrewPosY_06);
			this.LightweightTags.Add(this.ScrewPosY_07);
			this.LightweightTags.Add(this.ScrewPosY_08);
			this.LightweightTags.Add(this.ScrewPosY_09);
			this.LightweightTags.Add(this.ScrewPosY_10);
			this.LightweightTags.Add(this.ScrewPosY_11);
			this.LightweightTags.Add(this.ScrewPosY_12);
			this.LightweightTags.Add(this.ScrewPosY_13);
			this.LightweightTags.Add(this.ScrewPosY_14);
			this.LightweightTags.Add(this.ScrewPosY_15);
			this.LightweightTags.Add(this.ScrewPosY_16);
			this.LightweightTags.Add(this.ScrewPosY_17);
			this.LightweightTags.Add(this.ScrewPosY_18);
			this.LightweightTags.Add(this.ScrewPosY_19);
			this.LightweightTags.Add(this.ScrewPosY_20);
			this.GlobalDataItems.Add(this.ScrewPosZ_01);
			this.GlobalDataItems.Add(this.ScrewPosZ_02);
			this.LightweightTags.Add(this.ScrewPosZ_03);
			this.GlobalDataItems.Add(this.ScrewPosZ_04);
			this.GlobalDataItems.Add(this.ScrewPosZ_05);
			this.LightweightTags.Add(this.ScrewPosZ_06);
			this.LightweightTags.Add(this.ScrewPosZ_07);
			this.LightweightTags.Add(this.ScrewPosZ_08);
			this.LightweightTags.Add(this.ScrewPosZ_09);
			this.LightweightTags.Add(this.ScrewPosZ_10);
			this.LightweightTags.Add(this.ScrewPosZ_11);
			this.LightweightTags.Add(this.ScrewPosZ_12);
			this.LightweightTags.Add(this.ScrewPosZ_13);
			this.LightweightTags.Add(this.ScrewPosZ_14);
			this.LightweightTags.Add(this.ScrewPosZ_15);
			this.LightweightTags.Add(this.ScrewPosZ_16);
			this.LightweightTags.Add(this.ScrewPosZ_17);
			this.LightweightTags.Add(this.ScrewPosZ_18);
			this.LightweightTags.Add(this.ScrewPosZ_19);
			this.LightweightTags.Add(this.ScrewPosZ_20);
			this.GlobalDataItems.Add(this.ScrewID_01);
			this.GlobalDataItems.Add(this.ScrewID_02);
			this.GlobalDataItems.Add(this.ScrewID_03);
			this.GlobalDataItems.Add(this.ScrewID_04);
			this.GlobalDataItems.Add(this.ScrewID_05);
			this.GlobalDataItems.Add(this.ScrewID_06);
			this.GlobalDataItems.Add(this.ScrewID_07);
			this.GlobalDataItems.Add(this.ScrewID_08);
			this.GlobalDataItems.Add(this.ScrewID_09);
			this.GlobalDataItems.Add(this.ScrewID_10);
			this.LightweightTags.Add(this.ScrewID_11);
			this.LightweightTags.Add(this.ScrewID_12);
			this.LightweightTags.Add(this.ScrewID_13);
			this.LightweightTags.Add(this.ScrewID_14);
			this.LightweightTags.Add(this.ScrewID_15);
			this.LightweightTags.Add(this.ScrewID_16);
			this.LightweightTags.Add(this.ScrewID_17);
			this.LightweightTags.Add(this.ScrewID_18);
			this.LightweightTags.Add(this.ScrewID_19);
			this.LightweightTags.Add(this.ScrewID_20);
			this.GlobalDataItems.Add(this.Tag02);
			this.PollGroup1.Interval = 500;
			this.PollGroup1.Name = "PollGroup1";
			this.PollGroup2.Interval = 500;
			this.PollGroup2.Name = "PollGroup2";
			this.PollGroup3.Interval = 500;
			this.PollGroup3.Name = "PollGroup3";
			this.PollGroup4.Interval = 500;
			this.PollGroup4.Name = "PollGroup4";
			this.PollGroup5.Interval = 500;
			this.PollGroup5.Name = "PollGroup5";
			this.PollGroups.Add(this.PollGroup1);
			this.PollGroups.Add(this.PollGroup2);
			this.PollGroups.Add(this.PollGroup3);
			this.PollGroups.Add(this.PollGroup4);
			this.PollGroups.Add(this.PollGroup5);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Tags));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
